// <copyright file="ShipType.cs" company="Endjin Limited">
// Copyright (c) Endjin Limited. All rights reserved.
// </copyright>

namespace Ais.Net;

/// <summary>
/// Ship types.
/// </summary>
public enum ShipType
{
    NotAvailable = 0,

    ScienceOrResearchVessel = 1,
    TrainingVessel = 2,
    GovernmentOwnedOrOperatedShip = 3,
    IceBreaker = 4,
    AidsToNavigationTender = 5,
    CableLayer = 6,
    PipeLayer = 7,
    SpecialPurposeReserved8 = 8,
    SpecialPurposeNoAdditionalInformation = 9,

    SupportVesselReserved10 = 10,
    FloatingProductionStorageAndOffloadingVessel = 11,
    FishFactoryShip = 12,
    FishFarmSupportVessel = 13,
    OffshoreSupportVessel = 14,
    SupportVesselReserved15 = 15,
    SupportVesselReserved16 = 16,
    ConstructionVessel = 17,
    CrewBoat = 18,
    SupportVesselNoAdditionalInformation = 19,

    WingInGroundAll = 20,
    WingInGroundHazardousCategoryX = 21,
    WingInGroundHazardousCategoryY = 22,
    WingInGroundHazardousCategoryZ = 23,
    WingInGroundHazardousCategoryOs = 24,
    WingInGroundReserved25 = 25,
    WingInGroundReserved26 = 26,
    WingInGroundReserved27 = 27,
    WingInGroundReserved28 = 28,
    WingInGroundNoAdditionalInformation = 29,

    Fishing = 30,
    Towing = 31,
    TowingLengthOver200OmrBreadthOver25m = 32,
    Dredger = 33,
    DivingVessel = 34,
    WarshipOrNavalAuxiliary = 35,
    Sailing = 36,
    PleasureMotorCraft = 37,
    Trawler = 38,
    PatrolVessel = 39,

    HighSpeedCraftAll = 40,
    HighSpeedCraftHazardousCategoryX = 41,
    HighSpeedCraftHazardousCategoryY = 42,
    HighSpeedCraftHazardousCategoryZ = 43,
    HighSpeedCraftHazardousCategoryOs = 44,
    HighSpeedCraftPassenger = 45,
    HighSpeedCraftRoRo = 46,
    HighSpeedCraftReserved47 = 47,
    HighSpeedCraftReserved48 = 48,
    HighSpeedCraftNoAdditionalInformation = 49,

    PilotVessel = 50,
    SearchAndRescueVessel = 51,
    Tug = 52,
    PortOrFishTender = 53,
    AntiPollutionOrFirefightingResponder = 54,
    LawEnforcementVessel = 55,
    SpareLocalVessel56 = 56,
    SpareLocalVessel57 = 57,
    MedicalTransport = 58,
    ShipNotPartyToArmedConflict = 59,

    PassengerAll = 60,
    PassengerHazardousCategoryX = 61,
    PassengerHazardousCategoryY = 62,
    PassengerHazardousCategoryZ = 63,
    PassengerHazardousCategoryOs = 64,
    PassengerCruiseShip = 65,
    PassengerFerryShip = 66,
    PassengerExcursionShip = 67,
    PassengerReserved68 = 68,
    PassengerNoAdditionalInformation = 69,

    CargoAll = 70,
    CargoHazardousCategoryX = 71,
    CargoHazardousCategoryY = 72,
    CargoHazardousCategoryZ = 73,
    CargoHazardousCategoryOs = 74,
    CargoBulkCarrier = 75,
    CargoContainerShip = 76,
    CargoRollOnRollOffCarrier = 77,
    CargoLandingCraft = 78,
    CargoNoAdditionalInformation = 79,

    TankerAll = 80,
    TankerHazardousCategoryX = 81,
    TankerHazardousCategoryY = 82,
    TankerHazardousCategoryZ = 83,
    TankerHazardousCategoryOs = 84,
    TankerNonHazardousOrNonPollutantCarrier = 85,
    TankerIntegratedOrArticulatedTugAndBarge = 86,
    TankerReserved87 = 87,
    TankerReserved88 = 88,
    TankerNoAdditionalInformation = 89,

    OtherAll = 90,
    OtherHazardousCategoryX = 91,
    OtherHazardousCategoryY = 92,
    OtherHazardousCategoryZ = 93,
    OtherHazardousCategoryOs = 94,
    OtherReserved95 = 95,
    OtherReserved96 = 96,
    OtherReserved97 = 97,
    OtherReserved98 = 98,
    OtherNoAdditionalInformation = 99,
}
